version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - supabase/.env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./ui:/app/ui
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - supabase/.env
    environment:
      - REDIS_URL=redis://redis:6379
    command: dramatiq queue_manager

volumes:
  redis_data: